### ISSUE TITLE
Don't show path/symbol error for external dependencies.

### ISSUE THREAD

**Issue by jchild3rs** [Fedott/WebStormRequireJsPlugin#31]
![screen shot 2014-09-14 at 1 37 25 pm](https://cloud.githubusercontent.com/assets/692979/4264834/d85d34e8-3c35-11e4-9d64-a4bfed414e4a.png)

![screen shot 2014-09-14 at 1 40 23 pm](https://cloud.githubusercontent.com/assets/692979/4264847/3f8b5050-3c36-11e4-8d48-64a3e92f6e2b.png)

**Comment by just-boris** [comment]
+1
