### ISSUE TITLE
Won't load when running IDEA on Java 6

### ISSUE THREAD

**Issue by mkw** [Fedott/WebStormRequireJsPlugin#40]
I realize Java 6 is ancient at this point, but IDEA for JDK 8 for OS X is still pretty much unusable for stability and battery reasons.  Any chance you could make it work on JDK6 again?

**Comment by Fedott** [comment]
Hi. It's error.
I fixed this and upload new version, with support Java 6 bytecode.

**Comment by mkw** [comment]
Thanks!
