### ISSUE TITLE
Unable to update to 0.22.1 on PhpStorm 8.0.3

### ISSUE THREAD

**Issue by theNailz** [Fedott/WebStormRequireJsPlugin#41]
PhpStorm offers to update this plugin from 0.21 to 0.22.1, but after pressing "Update" nothng happens. After checking the PhpStorm logs, I see this related message:
```2015-04-01 10:04:44,182 [71055547]   INFO - Settings.impl.PluginDownloader - Plugin com.fedot.idea.requirejs is incompatible with current installation (since: 141, until: null) ```

Now I believe Phpstorm 8.0.3 (latest stable?) is version 139.. Does this make it a PhpStorm or RequireJS bug?

**Comment by Fedott** [comment]
Hi.
Update v0.22, released only for make compatible IDEA 14.1 and products based on him.
In v0.22 not have new features.
