### ISSUE TITLE
Problem with jsx files

### ISSUE THREAD

**Issue by umidbekkarimov** [Fedott/WebStormRequireJsPlugin#43]
Currently i'm using `jsx-requirejs-plugin`

When tring to include `*.jsx` file `'jsx!src/ui-components/Checkbox'`,
webstorm plugins looks for `Checkbox.js` not for `Checkbox.jsx` as expected

And only when i use `'jsx!src/ui-components/Checkbox.jsx'` it looks for `Checkbox.jsx`, but after that browser tries to load `src/ui-components/Checkbox.jsx.jsx` file

**Comment by merqlove** [comment]
Same here
