### ISSUE TITLE
[Feature request] Handlebars templates plugin support

### ISSUE THREAD

**Issue by josser** [Fedott/WebStormRequireJsPlugin#44]
Hi. First of all, thank you very much for your work!

Is it possible to add support for handlebars-symbols, i.e: 

```javascript
define(['marionette', 'hbs!templates/landing'], function (Marionette, template) {

    return Marionette.LayoutView.extend({
        template: template      
    });
});
```

In current version plugin can resolve only tpl! but don't know anything about hbs. 

Thanks!

**Comment by kusmierz** [comment]
+1
