### ISSUE TITLE
Loader plugins yield "cannot resolve symbol"

### ISSUE THREAD

**Issue by IARI** [Fedott/WebStormRequireJsPlugin#52]
Hi. First off, thanks a lot for your work on this plugin!

I'm using loader plugins from time  to time, and since thats custom code, i suppose it's not possible to add meaningful support for them. However, it would be nice, if they didn't cause errors (cannot resolve symbol)

**Comment by norbertas-gaulia** [comment]
All is working pretty well, please reffer to test cases inside this project. 
You need to set base path of front-end files, then set relative path (to base path)  where your requirejs config file is. First line in this file should be `require([`  or `require.config([`

Supported config files:
https://github.com/Fedott/WebStormRequireJsPlugin/tree/699d69004a76510f3001e6ea154ede200767c956/testData/public/config

**Comment by norbertas-gaulia** [comment]
+1 would be good if 

```
define([
        'image!awsum.jpg',
        'json!data/foo.json',
        'noext!js/bar.php',
        'mdown!data/lorem_ipsum.md',
        'async!http://maps.google.com/maps/api/js?sensor=false',
        'goog!search,1',
        'font!google'
    ], function(){
      
    }
); 
```

wouldn't throw a critical error.

**Comment by jchild3rs** [comment]
+1
